import type { Metadata } from "next";
import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";
import Image from "next/image";
import Script from "next/script";
import { ThemeProvider } from "next-themes";
import BackRedirect from "@/components/BackRedirect";

const _bricolageGrotesque = Bricolage_Grotesque({
	variable: "--font-bricolage-grotesque",
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${_bricolageGrotesque.variable} antialiased`}>
				<ThemeProvider
					attribute="data-theme"
					defaultTheme="dark"
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>

				{/* Meta Pixel Code */}
				<Script id="meta-pixel-script" strategy="afterInteractive">
					{`
					!function(f,b,e,v,n,t,s)
					{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
					n.callMethod.apply(n,arguments):n.queue.push(arguments)};
					if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
					n.queue=[];t=b.createElement(e);t.async=!0;
					t.src=v;s=b.getElementsByTagName(e)[0];
					s.parentNode.insertBefore(t,s)}(window, document,'script',
					'https://connect.facebook.net/en_US/fbevents.js');
					fbq('init', '1879517062811289');
					fbq('track', 'PageView');
					`}
				</Script>
				<noscript>
					<Image
						height="1"
						alt=""
						width="1"
						style={{ display: "none" }}
						src="https://www.facebook.com/tr?id=1879517062811289&ev=PageView&noscript=1"
					/>
				</noscript>
				{/* End Meta Pixel Code */}

				<Script
					id="utmify-script"
					strategy="afterInteractive"
					src="https://cdn.utmify.com.br/scripts/utms/latest.js"
					data-utmify-prevent-xcod-sck
					data-utmify-prevent-subids
					async
					defer
				/>

				<BackRedirect />
			</body>
		</html>
	);
}
