export const categories = [
	{ id: "cat-01", name: "Massas" },
	{ id: "cat-02", name: "Lanches" },
	{ id: "cat-03", name: "Frutos do Mar" },
	{ id: "cat-04", name: "Sobremesas" },
	{ id: "cat-05", name: "Carnes" },
	{ id: "cat-06", name: "Saladas" },
	{ id: "cat-07", name: "Sopas e Cremes" },
	{ id: "cat-08", name: "Acompanhamentos" },
	{ id: "cat-09", name: "Bebidas" },
	{ id: "cat-10", name: "Café da Manhã" },
];

export const recipes = [
	{
		id: "1",
		title: "🍝 Carbonara Rápida e Saborosa",
		description:
			"Um prato italiano clássico, com molho cremoso de ovos, queijo pecorino e bacon crocante. Fácil de fazer e irresistível!",
		image:
			"https://images.unsplash.com/photo-1588013273468-ce6974fa3bfd?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de espaguete",
			"100g de bacon ou pancetta",
			"2 gemas de ovo",
			"50g de queijo Pecorino ou Parmesão ralado",
			"Pimenta do reino a gosto",
		],
		instructions: [
			"Cozinhe o espaguete conforme as instruções da embalagem.",
			"Enquanto isso, frite o bacon até ficar crocante e reserve.",
			"Em uma tigela, misture as gemas, o queijo e a pimenta.",
			"Escorra o macarrão, adicione o bacon e, fora do fogo, despeje a mistura de ovos, mexendo rapidamente para criar um molho cremoso.",
		],
	},
	{
		id: "2",
		title: "🍔 Hambúrguer Smash Suculento",
		description:
			"Hambúrguer com crosta crocante e interior suculento, feito em minutos na chapa. Perfeito para um lanche rápido e delicioso!",
		image:
			"https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"150g de carne moída",
			"1 pão de hambúrguer",
			"1 fatia de queijo cheddar",
			"Sal e pimenta a gosto",
			"Alface, tomate e molho de sua preferência",
		],
		instructions: [
			"Divida a carne em duas bolas e aqueça bem uma frigideira.",
			"Coloque as bolas de carne na frigideira e amasse com uma espátula (smash).",
			"Tempere com sal e pimenta e cozinhe por 2 minutos.",
			"Vire, adicione o queijo e cozinhe por mais 1 minuto.",
			"Monte o hambúrguer no pão com os acompanhamentos.",
		],
	},
	{
		id: "3",
		title: "🐟 Ceviche Peruano Refrescante",
		description:
			"Peixe fresco com limão, pimenta e coentro. Um prato leve, rápido e cheio de sabor, ideal para dias quentes!",
		image:
			"https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-03",
		ingredients: [
			"200g de peixe branco fresco (tilápia ou corvina)",
			"Suco de 4 limões",
			"1/2 cebola roxa fatiada",
			"1 pimenta dedo-de-moça picada",
			"Coentro picado a gosto",
			"Sal a gosto",
		],
		instructions: [
			"Corte o peixe em cubos pequenos.",
			"Em uma tigela de vidro, misture o peixe com o suco de limão e deixe marinar na geladeira por 15 minutos.",
			"Adicione a cebola roxa, a pimenta e o coentro.",
			"Tempere com sal, misture bem e sirva imediatamente.",
		],
	},
	{
		id: "4",
		title: "☕ Tiramisù Cremoso",
		description:
			"Sobremesa italiana com camadas de biscoito, café e creme de mascarpone. Fácil, sem forno e absolutamente deliciosa!",
		image:
			"https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"250g de queijo mascarpone",
			"2 gemas",
			"50g de açúcar",
			"1 xícara de café forte e frio",
			"1 pacote de biscoito champanhe",
			"Cacau em pó para polvilhar",
		],
		instructions: [
			"Bata as gemas com o açúcar até obter um creme claro.",
			"Adicione o mascarpone e misture delicadamente.",
			"Mergulhe rapidamente os biscoitos no café e faça uma camada em uma travessa.",
			"Cubra com uma camada do creme de mascarpone. Repita as camadas.",
			"Leve à geladeira por pelo menos 4 horas e polvilhe cacau em pó antes de servir.",
		],
	},
	{
		id: "5",
		title: "🍗 Frango Xadrez Colorido",
		description:
			"Frango com pimentões, cebola e amendoim em molho agridoce. Um prato rápido, vibrante e cheio de sabor!",
		image:
			"https://images.unsplash.com/photo-1598515598523-245484a87aa4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de peito de frango em cubos",
			"1/2 pimentão verde",
			"1/2 pimentão vermelho",
			"1/2 cebola",
			"2 colheres de sopa de shoyu",
			"1 colher de sopa de amido de milho",
			"Amendoim torrado a gosto",
		],
		instructions: [
			"Tempere o frango com sal e pimenta.",
			"Em uma frigideira grande (wok), doure o frango e reserve.",
			"Na mesma frigideira, refogue a cebola e os pimentões.",
			"Dissolva o amido no shoyu e adicione à frigideira, mexendo até engrossar.",
			"Volte o frango para a frigideira, adicione o amendoim, misture e sirva.",
		],
	},
	{
		id: "6",
		title: "🌮 Tacos al Pastor Caseiros",
		description:
			"Tacos mexicanos com porco e abacaxi, cheios de sabor. Simples de preparar e perfeitos para qualquer ocasião!",
		image:
			"https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"300g de lombo de porco em tiras finas",
			"2 fatias de abacaxi em cubos",
			"1 colher de chá de páprica",
			"Suco de 1 laranja",
			"Tortillas de milho",
			"Coentro e cebola picados para servir",
		],
		instructions: [
			"Marine o porco na páprica e suco de laranja por 15 minutos.",
			"Grelhe o porco em uma frigideira quente até dourar.",
			"Adicione o abacaxi e cozinhe por mais 2 minutos.",
			"Aqueça as tortillas e sirva a carne com o abacaxi, coentro e cebola.",
		],
	},
	{
		id: "7",
		title: "🍜 Pad Thai Rápido",
		description:
			"Macarrão de arroz frito com camarão, tofu e molho agridoce. Um prato tailandês fácil, rápido e incrivelmente gostoso!",
		image:
			"https://images.unsplash.com/photo-1626081499702-8a9a5a8f4ab4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"150g de macarrão de arroz",
			"100g de camarão",
			"50g de tofu firme",
			"2 colheres de sopa de molho de peixe",
			"1 colher de sopa de açúcar",
			"Suco de 1 limão",
			"Amendoim picado e broto de feijão para servir",
		],
		instructions: [
			"Cozinhe o macarrão de arroz e reserve.",
			"Em uma wok, salteie o camarão e o tofu.",
			"Adicione o macarrão cozido, o molho de peixe, o açúcar e o suco de limão.",
			"Misture bem e sirva com amendoim picado e broto de feijão por cima.",
		],
	},
	{
		id: "8",
		title: "🥗 Salada Caprese",
		description:
			"Tomate, muçarela de búfala e manjericão fresco com azeite de oliva. Uma salada italiana refrescante e pronta em minutos!",
		image:
			"https://images.unsplash.com/photo-1579113800036-3b6b7a8e5f19?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"2 tomates maduros",
			"125g de muçarela de búfala",
			"Folhas de manjericão fresco",
			"Azeite de oliva extra virgem",
			"Sal e pimenta do reino a gosto",
		],
		instructions: [
			"Fatie os tomates e a muçarela.",
			"Intercale as fatias de tomate e queijo em um prato.",
			"Distribua as folhas de manjericão por cima.",
			"Regue com azeite de oliva e tempere com sal e pimenta.",
		],
	},
	{
		id: "9",
		title: "🥪 Sanduíche de Frango Grelhado",
		description:
			"Peito de frango grelhado com alface, tomate e maionese em pão macio. Um lanche rápido e delicioso para qualquer hora!",
		image:
			"https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 filé de frango",
			"2 fatias de pão de forma",
			"Folhas de alface",
			"1/2 tomate fatiado",
			"Maionese a gosto",
			"Sal e pimenta",
		],
		instructions: [
			"Tempere o filé de frango com sal e pimenta e grelhe até dourar.",
			"Toste as fatias de pão.",
			"Passe maionese em uma fatia de pão, adicione a alface, o tomate e o frango grelhado.",
			"Cubra com a outra fatia de pão e sirva.",
		],
	},
	{
		id: "10",
		title: "🍳 Omelete de Queijo e Ervas",
		description:
			"Ovos batidos com queijo derretido e ervas frescas. Simples, rápido e perfeito para o café da manhã ou jantar leve!",
		image:
			"https://images.unsplash.com/photo-1609951659545-926d708d7524?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.5,
		isPublic: true,
		categoryId: "cat-10",
		ingredients: [
			"2 ovos",
			"2 colheres de sopa de leite",
			"30g de queijo muçarela ralado",
			"Ervas frescas picadas (salsinha, cebolinha)",
			"Sal e pimenta a gosto",
			"1 colher de chá de manteiga",
		],
		instructions: [
			"Bata os ovos com o leite, sal e pimenta.",
			"Derreta a manteiga em uma frigideira antiaderente.",
			"Despeje os ovos batidos e cozinhe em fogo baixo.",
			"Quando a base estiver firme, espalhe o queijo e as ervas sobre metade da omelete.",
			"Dobre e cozinhe por mais um minuto. Sirva quente.",
		],
	},
	{
		id: "11",
		title: "🥞 Panquecas Fofas",
		description:
			"Panquecas leves e douradas, perfeitas com mel, frutas ou geleia. Fáceis de fazer e ideais para um café da manhã especial!",
		image:
			"https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-10",
		ingredients: [
			"1 xícara de farinha de trigo",
			"1 colher de sopa de açúcar",
			"1 colher de chá de fermento em pó",
			"1 ovo",
			"1 xícara de leite",
			"2 colheres de sopa de manteiga derretida",
		],
		instructions: [
			"Em uma tigela, misture os ingredientes secos.",
			"Em outra, misture o ovo, o leite e a manteiga.",
			"Junte os ingredientes úmidos aos secos e misture até incorporar.",
			"Aqueça uma frigideira e despeje porções da massa.",
			"Cozinhe até formar bolhas, vire e doure o outro lado.",
		],
	},
	{
		id: "12",
		title: "🍲 Sopa de Abóbora Cremosa",
		description:
			"Sopa aveludada de abóbora com toque de creme de leite. Fácil, reconfortante e pronta em poucos minutos!",
		image:
			"https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-07",
		ingredients: [
			"500g de abóbora em cubos",
			"1/2 cebola picada",
			"1 dente de alho",
			"500ml de caldo de legumes",
			"50ml de creme de leite",
			"Sal e noz-moscada a gosto",
		],
		instructions: [
			"Refogue a cebola e o alho em uma panela.",
			"Adicione a abóbora e o caldo de legumes.",
			"Cozinhe até a abóbora ficar macia.",
			"Bata tudo no liquidificador até obter um creme liso.",
			"Volte para a panela, adicione o creme de leite, tempere com sal e noz-moscada e aqueça sem ferver.",
		],
	},
	{
		id: "13",
		title: "🍤 Camarão ao Alho",
		description:
			"Camarões salteados com alho, azeite e salsinha. Um prato rápido, saboroso e perfeito para impressionar!",
		image:
			"https://images.unsplash.com/photo-1599218143298-5345a638386a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-03",
		ingredients: [
			"300g de camarão limpo",
			"3 dentes de alho fatiados",
			"3 colheres de sopa de azeite",
			"Salsinha picada a gosto",
			"Sal e pimenta a gosto",
		],
		instructions: [
			"Aqueça o azeite em uma frigideira e doure o alho.",
			"Adicione os camarões e salteie por 3-4 minutos, até ficarem rosados.",
			"Tempere com sal e pimenta.",
			"Finalize com a salsinha picada e sirva imediatamente.",
		],
	},
	{
		id: "14",
		title: "🥙 Wrap de Atum",
		description:
			"Atum, alface, tomate e maionese em uma tortilla macia. Um lanche saudável e rápido para qualquer momento!",
		image:
			"https://images.unsplash.com/photo-1619881599339-9a678075b0e2?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 lata de atum",
			"2 colheres de sopa de maionese",
			"1 tortilla de trigo",
			"Folhas de alface",
			"Tomate picado",
		],
		instructions: [
			"Misture o atum com a maionese.",
			"Aqueça a tortilla levemente.",
			"Espalhe a pasta de atum sobre a tortilla.",
			"Adicione a alface e o tomate.",
			"Enrole o wrap e sirva.",
		],
	},
	{
		id: "15",
		title: "🍅 Bruschetta de Tomate",
		description:
			"Pão torrado com tomate fresco, manjericão e azeite. Uma entrada italiana simples e cheia de sabor!",
		image:
			"https://images.unsplash.com/photo-1505253716362-afb74990d977?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"4 fatias de pão italiano",
			"2 tomates picados sem sementes",
			"Folhas de manjericão fresco",
			"1 dente de alho",
			"Azeite de oliva",
			"Sal",
		],
		instructions: [
			"Toste as fatias de pão.",
			"Esfregue levemente o dente de alho no pão tostado.",
			"Em uma tigela, misture o tomate, o manjericão, o azeite e o sal.",
			"Coloque a mistura sobre as fatias de pão e sirva.",
		],
	},
	{
		id: "16",
		title: "🍴 Macarrão com Molho Pesto",
		description:
			"Macarrão com molho de manjericão, parmesão e nozes. Rápido, fresco e perfeito para um jantar leve!",
		image:
			"https://images.unsplash.com/photo-1598866594240-a71618546216?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de macarrão",
			"2 xícaras de manjericão fresco",
			"1/2 xícara de queijo parmesão ralado",
			"1/4 xícara de nozes ou pinoli",
			"1 dente de alho",
			"1/2 xícara de azeite",
		],
		instructions: [
			"Cozinhe o macarrão.",
			"No processador, bata o manjericão, o parmesão, as nozes e o alho.",
			"Com o processador ligado, adicione o azeite em fio até formar um molho.",
			"Misture o molho pesto ao macarrão cozido e sirva.",
		],
	},
	{
		id: "17",
		title: "🥗 Salada de Frango Caesar",
		description:
			"Alface crocante, frango grelhado, croutons e molho Caesar. Uma salada clássica e fácil de preparar!",
		image:
			"https://images.unsplash.com/photo-1550305080-4e029753abcf?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1 pé de alface romana",
			"1 filé de frango grelhado e fatiado",
			"Croutons a gosto",
			"Queijo parmesão ralado",
			"Molho Caesar pronto",
		],
		instructions: [
			"Lave e rasgue as folhas de alface.",
			"Em uma saladeira, misture a alface, o frango e os croutons.",
			"Regue com o molho Caesar e polvilhe com queijo parmesão.",
			"Misture bem e sirva.",
		],
	},
	{
		id: "18",
		title: "🍕 Pizza de Frigideira",
		description:
			"Pizza caseira feita na frigideira com molho de tomate, queijo e seus toppings favoritos. Rápida e deliciosa!",
		image:
			"https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 massa de pizza pronta (ou massa de wrap)",
			"3 colheres de sopa de molho de tomate",
			"100g de queijo muçarela ralado",
			"Orégano e toppings a gosto (calabresa, manjericão)",
		],
		instructions: [
			"Aqueça uma frigideira antiaderente em fogo baixo.",
			"Coloque a massa na frigideira.",
			"Espalhe o molho de tomate, o queijo e os toppings.",
			"Tampe a frigideira e cozinhe por 5-7 minutos, ou até o queijo derreter e a base ficar crocante.",
		],
	},
	{
		id: "19",
		title: "🥑 Guacamole Caseiro",
		description:
			"Abacate cremoso com limão, tomate, cebola e coentro. Perfeito com nachos ou como acompanhamento!",
		image:
			"https://images.unsplash.com/photo-1595016523333-285b3a4a7113?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"1 abacate maduro",
			"1/2 tomate picado",
			"1/4 cebola roxa picada",
			"Suco de 1/2 limão",
			"Coentro picado a gosto",
			"Sal",
		],
		instructions: [
			"Amasse o abacate com um garfo.",
			"Adicione o tomate, a cebola, o coentro e o suco de limão.",
			"Tempere com sal e misture bem.",
			"Sirva com nachos ou como acompanhamento.",
		],
	},
	{
		id: "20",
		title: "🍓 Smoothie de Morango e Banana",
		description:
			"Smoothie refrescante com morangos, banana e iogurte. Ideal para um lanche rápido ou café da manhã saudável!",
		image:
			"https://images.unsplash.com/photo-1610970881699-44a5c8a0f49a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-09",
		ingredients: [
			"1 xícara de morangos congelados",
			"1 banana madura",
			"1/2 xícara de iogurte natural",
			"1/4 xícara de leite ou água",
		],
		instructions: [
			"Coloque todos os ingredientes no liquidificador.",
			"Bata até obter uma mistura cremosa e homogênea.",
			"Se necessário, adicione mais líquido para atingir a consistência desejada.",
			"Sirva imediatamente.",
		],
	},
	{
		id: "21",
		title: "🥚 Ovos Mexidos Cremosos",
		description:
			"Ovos batidos cozidos lentamente com um toque de creme de leite. Simples, rápido e perfeito para o café da manhã!",
		image:
			"https://images.unsplash.com/photo-1598103442344-47333e043c14?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-10",
		ingredients: [
			"3 ovos",
			"2 colheres de sopa de creme de leite",
			"1 colher de chá de manteiga",
			"Sal e pimenta a gosto",
			"Cebolinha picada para decorar",
		],
		instructions: [
			"Bata os ovos com o creme de leite, sal e pimenta.",
			"Derreta a manteiga em uma frigideira em fogo baixo.",
			"Despeje os ovos e cozinhe lentamente, mexendo com uma espátula.",
			"Retire do fogo quando ainda estiverem úmidos.",
			"Decore com cebolinha e sirva.",
		],
	},
	{
		id: "22",
		title: "🥖 Torrada com Abacate",
		description:
			"Pão torrado com abacate cremoso, limão e um toque de sal. Um café da manhã saudável e rápido!",
		image:
			"https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-10",
		ingredients: [
			"2 fatias de pão integral",
			"1/2 abacate maduro",
			"Suco de 1/4 de limão",
			"Sal e pimenta a gosto",
			"Pimenta calabresa (opcional)",
		],
		instructions: [
			"Toste as fatias de pão.",
			"Amasse o abacate com um garfo e misture com o suco de limão, sal e pimenta.",
			"Espalhe a mistura de abacate sobre as torradas.",
			"Polvilhe com pimenta calabresa, se desejar, e sirva.",
		],
	},
	{
		id: "23",
		title: "🍴 Penne ao Molho de Tomate",
		description:
			"Macarrão penne com molho de tomate caseiro e manjericão. Um prato simples e cheio de sabor!",
		image:
			"https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de macarrão penne",
			"1 lata de tomate pelado",
			"1 dente de alho picado",
			"Azeite",
			"Folhas de manjericão",
			"Sal e açúcar a gosto",
		],
		instructions: [
			"Cozinhe o macarrão.",
			"Em uma panela, refogue o alho no azeite.",
			"Adicione o tomate pelado e amasse com um garfo.",
			"Tempere com sal e uma pitada de açúcar para cortar a acidez.",
			"Cozinhe por 10 minutos, adicione o manjericão e sirva sobre o macarrão.",
		],
	},
	{
		id: "24",
		title: "🥗 Salada de Quinoa",
		description:
			"Quinoa com tomate cereja, pepino, cebola roxa e molho de limão. Leve, saudável e pronta em minutos!",
		image:
			"https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1 xícara de quinoa cozida",
			"1/2 xícara de tomate cereja cortado ao meio",
			"1/2 pepino em cubos",
			"1/4 de cebola roxa picada",
			"Suco de 1 limão",
			"Azeite e sal",
		],
		instructions: [
			"Em uma tigela, misture a quinoa cozida, o tomate, o pepino e a cebola.",
			"Tempere com suco de limão, azeite e sal.",
			"Misture bem e sirva fria ou em temperatura ambiente.",
		],
	},
	{
		id: "25",
		title: "🍗 Nuggets Caseiros",
		description:
			"Pedaços de frango empanados e fritos até ficarem crocantes. Fácil e perfeito para crianças e adultos!",
		image:
			"https://images.unsplash.com/photo-1562967916-eb82221dfb32?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de peito de frango moído",
			"1/2 xícara de farinha de rosca",
			"1 ovo",
			"Sal e páprica a gosto",
			"Óleo para fritar",
		],
		instructions: [
			"Tempere o frango moído com sal e páprica.",
			"Modele pequenos nuggets.",
			"Passe cada nugget no ovo batido e depois na farinha de rosca.",
			"Frite em óleo quente até dourar.",
			"Escorra em papel toalha e sirva.",
		],
	},
	{
		id: "26",
		title: "🍮 Pudim de Iogurte",
		description:
			"Sobremesa leve com iogurte, leite condensado e gelatina. Fácil de fazer e refrescante!",
		image:
			"https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 lata de leite condensado",
			"1 lata de iogurte natural (use a lata como medida)",
			"1 envelope de gelatina sem sabor",
			"Calda de caramelo",
		],
		instructions: [
			"Prepare a gelatina conforme as instruções da embalagem.",
			"No liquidificador, bata o leite condensado, o iogurte e a gelatina dissolvida.",
			"Despeje em uma forma caramelizada.",
			"Leve à geladeira por pelo menos 4 horas.",
		],
	},
	{
		id: "27",
		title: "🥟 Bolinho de Milho",
		description:
			"Bolinhos fritos de milho com queijo, crocantes por fora e macios por dentro. Um petisco rápido e saboroso!",
		image:
			"https://images.unsplash.com/photo-1625944239901-84c361154323?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"1 lata de milho escorrido",
			"1/2 xícara de farinha de trigo",
			"1 ovo",
			"50g de queijo ralado",
			"Sal e cebolinha a gosto",
			"Óleo para fritar",
		],
		instructions: [
			"Bata metade do milho no liquidificador.",
			"Misture com o restante do milho, a farinha, o ovo, o queijo, o sal e a cebolinha.",
			"Modele bolinhos com a ajuda de duas colheres.",
			"Frite em óleo quente até dourar.",
		],
	},
	{
		id: "28",
		title: "🍵 Chá Gelado de Hibisco",
		description:
			"Chá refrescante de hibisco com limão e um toque de açúcar. Perfeito para dias quentes!",
		image:
			"https://images.unsplash.com/photo-1542586924-e65a8135a18b?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-09",
		ingredients: [
			"2 colheres de sopa de flores de hibisco secas",
			"1 litro de água",
			"Suco de 1/2 limão",
			"Açúcar ou mel a gosto",
			"Gelo",
		],
		instructions: [
			"Ferva a água e adicione as flores de hibisco.",
			"Desligue o fogo, tampe e deixe em infusão por 5-10 minutos.",
			"Coe o chá e adoce a gosto.",
			"Adicione o suco de limão e deixe esfriar.",
			"Sirva com muito gelo.",
		],
	},
	{
		id: "29",
		title: "🥘 Arroz com Frango",
		description:
			"Arroz soltinho com pedaços de frango e temperos simples. Um prato caseiro e rápido para o dia a dia!",
		image:
			"https://images.unsplash.com/photo-1604909053233-3216a05334b3?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"1 xícara de arroz",
			"2 xícaras de água",
			"200g de peito de frango em cubos",
			"1/2 cebola picada",
			"1 dente de alho picado",
			"Sal e açafrão a gosto",
		],
		instructions: [
			"Refogue a cebola e o alho.",
			"Adicione o frango e doure.",
			"Acrescente o arroz e refogue por mais um minuto.",
			"Adicione a água, o sal e o açafrão.",
			"Cozinhe em fogo baixo com a panela semi-tampada até a água secar.",
		],
	},
	{
		id: "30",
		title: "🍫 Mousse de Chocolate",
		description:
			"Mousse cremosa de chocolate feita com poucos ingredientes. Uma sobremesa fácil e irresistível!",
		image:
			"https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.9,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 lata de creme de leite",
			"200g de chocolate meio amargo picado",
			"3 claras em neve",
			"3 colheres de sopa de açúcar",
		],
		instructions: [
			"Derreta o chocolate com o creme de leite em banho-maria ou no micro-ondas.",
			"Bata as claras em neve e adicione o açúcar aos poucos, até formar um merengue firme.",
			"Incorpore delicadamente o merengue à mistura de chocolate.",
			"Distribua em taças e leve à geladeira por 3 horas.",
		],
	},
	{
		id: "31",
		title: "🥩 Carne Moída com Batata",
		description:
			"Um clássico da cozinha caseira brasileira. Carne moída refogada com batatas em cubos, simples, nutritivo e delicioso.",
		image:
			"https://images.unsplash.com/photo-1619882199749-0c127a5c7a86?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de carne moída",
			"2 batatas médias em cubos",
			"1/2 cebola picada",
			"1 dente de alho picado",
			"Sal, pimenta e cheiro-verde a gosto",
		],
		instructions: [
			"Refogue a cebola e o alho em uma panela.",
			"Adicione a carne moída e cozinhe até dourar.",
			"Acrescente as batatas, cubra com água e tempere com sal e pimenta.",
			"Cozinhe até as batatas ficarem macias.",
			"Finalize com cheiro-verde.",
		],
	},
	{
		id: "32",
		title: "🍎 Torta de Maçã Rápida",
		description:
			"Uma sobremesa clássica com um atalho delicioso. Fatias de maçã com canela sobre uma base de massa folhada crocante.",
		image:
			"https://images.unsplash.com/photo-1589117919472-d69a726b6a1e?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 rolo de massa folhada pronta",
			"2 maçãs fatiadas",
			"2 colheres de sopa de açúcar",
			"1 colher de chá de canela em pó",
			"Gema para pincelar",
		],
		instructions: [
			"Abra a massa folhada em uma forma.",
			"Distribua as fatias de maçã sobre a massa.",
			"Misture o açúcar com a canela e polvilhe sobre as maçãs.",
			"Pincele as bordas com gema e asse em forno pré-aquecido a 180°C por 20 minutos.",
		],
	},
	{
		id: "33",
		title: "🥒 Salada de Pepino Japonesa",
		description:
			"Conhecida como 'Sunomono', esta salada agridoce de pepino com gergelim é super refrescante e fácil de fazer.",
		image:
			"https://images.unsplash.com/photo-1598994407889-927b529910a4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1 pepino japonês em fatias finas",
			"3 colheres de sopa de vinagre de arroz",
			"1 colher de sopa de açúcar",
			"1 pitada de sal",
			"Gergelim torrado a gosto",
		],
		instructions: [
			"Misture o vinagre, o açúcar e o sal até dissolver.",
			"Adicione o pepino fatiado e misture bem.",
			"Deixe marinar por 5 minutos na geladeira.",
			"Sirva polvilhado com gergelim.",
		],
	},
	{
		id: "34",
		title: "🥕 Tempurá de Legumes",
		description:
			"Legumes variados envoltos em uma massa leve e crocante. Um petisco japonês perfeito para qualquer ocasião.",
		image:
			"https://images.unsplash.com/photo-1630992915362-b79832735199?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"Legumes variados (cenoura, abobrinha, brócolis)",
			"1 xícara de farinha de trigo",
			"1 xícara de água gelada",
			"1 ovo",
			"Óleo para fritar",
		],
		instructions: [
			"Corte os legumes em palitos ou pedaços.",
			"Misture a farinha, a água gelada e o ovo para fazer a massa.",
			"Passe os legumes na massa e frite em óleo quente até dourar.",
			"Escorra em papel toalha e sirva.",
		],
	},
	{
		id: "35",
		title: "🥐 Croissant com Presunto e Queijo",
		description:
			"A combinação perfeita de massa folhada amanteigada com presunto e queijo derretido. Um lanche clássico e irresistível.",
		image:
			"https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 croissant pronto",
			"2 fatias de presunto",
			"2 fatias de queijo muçarela",
		],
		instructions: [
			"Corte o croissant ao meio.",
			"Recheie com o presunto e o queijo.",
			"Leve ao forno ou sanduicheira por alguns minutos, até o queijo derreter.",
			"Sirva quente.",
		],
	},
	{
		id: "36",
		title: "🍝 Espaguete com Almôndegas",
		description:
			"Um prato que agrada a todos: espaguete coberto com um rico molho de tomate e almôndegas suculentas.",
		image:
			"https://images.unsplash.com/photo-1586952051332-36d453658313?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de espaguete",
			"250g de almôndegas prontas ou caseiras",
			"1 lata de molho de tomate",
			"Manjericão fresco",
			"Queijo parmesão ralado",
		],
		instructions: [
			"Cozinhe o espaguete.",
			"Em uma panela, aqueça o molho de tomate e cozinhe as almôndegas por 10 minutos.",
			"Sirva o molho com as almôndegas sobre o espaguete.",
			"Finalize com manjericão e queijo parmesão.",
		],
	},
	{
		id: "37",
		title: "🍇 Salada de Frutas",
		description:
			"Uma mistura colorida e refrescante de frutas frescas. A sobremesa ou lanche perfeito para um dia saudável.",
		image:
			"https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 banana",
			"1 maçã",
			"1/2 mamão papaia",
			"10 uvas",
			"Suco de 1/2 laranja",
		],
		instructions: [
			"Pique todas as frutas em cubos.",
			"Coloque em uma tigela e misture.",
			"Regue com o suco de laranja para não escurecerem.",
			"Sirva gelada.",
		],
	},
	{
		id: "38",
		title: "🍗 Asinha de Frango na Airfryer",
		description:
			"Asinhas de frango temperadas e assadas na airfryer até ficarem douradas e super crocantes. Petisco perfeito!",
		image:
			"https://images.unsplash.com/photo-1628527984462-9b6330d4a57a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"500g de asinhas de frango",
			"Sal",
			"Páprica doce",
			"Alho em pó",
			"Azeite",
		],
		instructions: [
			"Tempere as asinhas com sal, páprica, alho em pó e um fio de azeite.",
			"Disponha na cesta da airfryer sem sobrepor.",
			"Asse a 200°C por 20-25 minutos, virando na metade do tempo.",
			"Sirva com seu molho preferido.",
		],
	},
	{
		id: "39",
		title: "🍅 Sopa de Tomate Assado",
		description:
			"Tomates assados com alho e ervas, transformados em uma sopa cremosa e cheia de sabor. Aconchegante e deliciosa.",
		image:
			"https://images.unsplash.com/photo-1598214886343-7c641b45e1b6?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-07",
		ingredients: [
			"4 tomates maduros",
			"2 dentes de alho",
			"1/2 cebola",
			"Azeite",
			"Caldo de legumes",
			"Manjericão",
		],
		instructions: [
			"Corte os tomates e a cebola, coloque em uma assadeira com o alho e regue com azeite. Asse por 15 min.",
			"Bata os legumes assados no liquidificador com o caldo de legumes.",
			"Aqueça a sopa, tempere com sal e sirva com folhas de manjericão.",
		],
	},
	{
		id: "40",
		title: "🥪 Sanduíche de Pasta de Atum",
		description:
			"Uma pasta cremosa de atum com maionese e cebola, perfeita para um lanche rápido, prático e saboroso.",
		image:
			"https://images.unsplash.com/photo-1625194659829-60a88c19434a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 lata de atum sólido",
			"3 colheres de sopa de maionese",
			"1/4 de cebola picada",
			"2 fatias de pão de forma",
			"Sal e pimenta",
		],
		instructions: [
			"Escorra o atum e misture com a maionese e a cebola.",
			"Tempere com sal e pimenta a gosto.",
			"Recheie o pão com a pasta de atum.",
			"Sirva imediatamente ou gelado.",
		],
	},
	{
		id: "41",
		title: "🍤 Salada de Camarão com Abacate",
		description:
			"Camarões suculentos, abacate cremoso e um molho cítrico. Uma salada leve, sofisticada e pronta em minutos.",
		image:
			"https://images.unsplash.com/photo-1587578399434-28a29f340b11?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"150g de camarão cozido",
			"1/2 abacate em cubos",
			"Mix de folhas verdes",
			"Suco de limão",
			"Azeite",
			"Coentro picado",
		],
		instructions: [
			"Em uma tigela, disponha as folhas verdes.",
			"Adicione o camarão cozido e o abacate.",
			"Tempere com suco de limão, azeite e sal.",
			"Finalize com coentro picado e sirva.",
		],
	},
	{
		id: "42",
		title: "🥚 Salada de Ovo",
		description:
			"Uma pasta cremosa de ovos cozidos com maionese e cebolinha. Perfeita para rechear sanduíches ou comer com torradas.",
		image:
			"https://images.unsplash.com/photo-1613138550154-15a822f40f33?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"3 ovos cozidos e picados",
			"3 colheres de sopa de maionese",
			"1 colher de sopa de cebolinha picada",
			"Sal e pimenta a gosto",
		],
		instructions: [
			"Cozinhe os ovos por 10 minutos, descasque e pique.",
			"Em uma tigela, misture os ovos picados com a maionese e a cebolinha.",
			"Tempere com sal e pimenta.",
			"Sirva como preferir.",
		],
	},
	{
		id: "43",
		title: "🍮 Flan de Baunilha com Caramelo",
		description:
			"Um flan cremoso e delicado com sabor de baunilha, coberto por uma calda de caramelo dourada. Sobremesa clássica e fácil.",
		image:
			"https://images.unsplash.com/photo-1487373220413-a9782a5879b9?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 lata de leite condensado",
			"A mesma medida de leite",
			"3 ovos",
			"1 colher de chá de essência de baunilha",
			"Calda de caramelo pronta",
		],
		instructions: [
			"Bata o leite condensado, o leite, os ovos e a baunilha no liquidificador.",
			"Despeje a mistura em uma forma caramelizada.",
			"Asse em banho-maria em forno a 180°C por cerca de 20 minutos (ou use forminhas individuais).",
			"Deixe esfriar e desenforme.",
		],
	},
	{
		id: "44",
		title: "🥔 Batata Rosti",
		description:
			"Uma torta de batata ralada, crocante por fora e macia por dentro. Pode ser servida como acompanhamento ou prato principal com recheio.",
		image:
			"https://images.unsplash.com/photo-1621852003738-64b5f32436a4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"2 batatas grandes",
			"Sal e pimenta a gosto",
			"Manteiga ou azeite",
		],
		instructions: [
			"Rale as batatas no ralo grosso e esprema para retirar o excesso de água.",
			"Tempere com sal e pimenta.",
			"Aqueça manteiga em uma frigideira e espalhe metade da batata, formando um disco.",
			"Cozinhe por 7-10 minutos, vire com a ajuda de um prato e doure o outro lado.",
		],
	},
	{
		id: "45",
		title: "🧀 Macarrão com Queijo (Mac 'n' Cheese)",
		description:
			"O prato de conforto definitivo. Macarrão envolto em um molho de queijo super cremoso e delicioso.",
		image:
			"https://images.unsplash.com/photo-1541783245547-a3d604567240?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de macarrão caracol",
			"1 xícara de leite",
			"1 xícara de queijo cheddar ralado",
			"1 colher de sopa de manteiga",
			"Sal",
		],
		instructions: [
			"Cozinhe o macarrão.",
			"Em uma panela, derreta a manteiga, adicione o leite e aqueça.",
			"Adicione o queijo aos poucos, mexendo até derreter e formar um molho cremoso.",
			"Misture o molho ao macarrão cozido e sirva.",
		],
	},
	{
		id: "46",
		title: "🍚 Risoto de Parmesão",
		description:
			"Um risoto básico e elegante, cremoso e cheio do sabor intenso do queijo parmesão. Perfeito como base para outras receitas.",
		image:
			"https://images.unsplash.com/photo-1595908129324-1a7333a0a3a4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"1 xícara de arroz arbóreo",
			"1/2 cebola picada",
			"Caldo de legumes quente",
			"1/2 xícara de queijo parmesão ralado",
			"1 colher de sopa de manteiga",
		],
		instructions: [
			"Refogue a cebola na manteiga.",
			"Adicione o arroz e refogue por 1 minuto.",
			"Vá adicionando o caldo de legumes aos poucos, mexendo sempre, até o arroz ficar 'al dente'.",
			"Desligue o fogo, adicione o parmesão e a manteiga, e misture bem para dar cremosidade.",
		],
	},
	{
		id: "47",
		title: "🥪 Sanduíche de Peru e Queijo Branco",
		description:
			"Uma opção de lanche leve e saudável. Peito de peru fatiado com queijo branco fresco em pão integral.",
		image:
			"https://images.unsplash.com/photo-1553909489-cd47e0907910?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"2 fatias de pão integral",
			"3 fatias de peito de peru",
			"2 fatias de queijo branco",
			"Folhas de alface",
			"Mostarda a gosto",
		],
		instructions: [
			"Passe mostarda em uma das fatias de pão.",
			"Monte o sanduíche com a alface, o peito de peru e o queijo branco.",
			"Feche com a outra fatia de pão e sirva.",
		],
	},
	{
		id: "48",
		title: "🍦 Sorvete de Banana com 1 Ingrediente",
		description:
			"A sobremesa mais fácil e saudável do mundo! Bananas congeladas batidas até virarem um sorvete cremoso.",
		image:
			"https://images.unsplash.com/photo-1625862431534-a7a5f8591430?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: ["2 bananas maduras congeladas em rodelas"],
		instructions: [
			"Coloque as rodelas de banana congelada em um processador de alimentos ou liquidificador potente.",
			"Bata até a mistura ficar lisa e cremosa, parecendo um sorvete.",
			"Sirva imediatamente.",
		],
	},
	{
		id: "49",
		title: "🥦 Frango com Brócolis ao Molho Shoyu",
		description:
			"Pedaços de frango e brócolis frescos salteados em um molho oriental simples. Um prato rápido e nutritivo para a semana.",
		image:
			"https://images.unsplash.com/photo-1606523849380-b554c6c8a33e?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de peito de frango em cubos",
			"1 maço de brócolis",
			"3 colheres de sopa de molho shoyu",
			"1 dente de alho picado",
			"Gengibre ralado a gosto",
		],
		instructions: [
			"Cozinhe o brócolis no vapor até ficar 'al dente' e reserve.",
			"Em uma frigideira, doure o frango com o alho e o gengibre.",
			"Adicione o shoyu e o brócolis cozido.",
			"Misture bem e sirva com arroz branco.",
		],
	},
	{
		id: "50",
		title: "🍿 Pipoca Doce com Chocolate",
		description:
			"A pipoca de cinema em casa, com uma calda de chocolate fácil que a deixa crocante e irresistível.",
		image:
			"https://images.unsplash.com/photo-1578849224348-5319dc3512b7?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1/2 xícara de milho para pipoca",
			"4 colheres de sopa de açúcar",
			"4 colheres de sopa de achocolatado em pó",
			"4 colheres de sopa de água",
			"2 colheres de sopa de óleo",
		],
		instructions: [
			"Em uma panela grande, coloque o óleo, o milho, o açúcar, o achocolatado e a água.",
			"Leve ao fogo médio, mexendo sempre até começar a estourar.",
			"Tampe a panela e agite ocasionalmente até parar de estourar.",
			"Despeje em uma travessa e espere esfriar para ficar crocante.",
		],
	},
	{
		id: "51",
		title: "🥗 Salada de Rúcula com Tomate Seco",
		description:
			"Uma salada com sabores marcantes: a picância da rúcula, a doçura do tomate seco e o salgado do queijo parmesão.",
		image:
			"https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1 maço de rúcula",
			"1/2 xícara de tomate seco picado",
			"Lâminas de queijo parmesão",
			"Azeite",
			"Redução de balsâmico (opcional)",
		],
		instructions: [
			"Lave e seque bem a rúcula.",
			"Em uma saladeira, misture a rúcula e o tomate seco.",
			"Regue com azeite e, se desejar, com a redução de balsâmico.",
			"Finalize com as lâminas de parmesão.",
		],
	},
	{
		id: "52",
		title: "🍴 Strogonoff de Frango Simples",
		description:
			"A versão mais prática do amado strogonoff. Frango em cubos, creme de leite, ketchup e mostarda. Rápido e delicioso.",
		image:
			"https://images.unsplash.com/photo-1618433381155-963c25627b43?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de frango em cubos",
			"1 lata de creme de leite",
			"2 colheres de sopa de ketchup",
			"1 colher de sopa de mostarda",
			"Sal e pimenta",
		],
		instructions: [
			"Tempere e doure o frango em uma panela.",
			"Abaixe o fogo e adicione o ketchup e a mostarda. Misture bem.",
			"Incorpore o creme de leite (sem o soro) e aqueça sem deixar ferver.",
			"Sirva com arroz e batata palha.",
		],
	},
	{
		id: "53",
		title: "🍮 Gelatina Colorida",
		description:
			"Uma sobremesa divertida e colorida que agrada crianças e adultos. Camadas de gelatina com um creme branco.",
		image:
			"https://images.unsplash.com/photo-1616504795923-97358c1c3ca4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"3 caixas de gelatina de sabores/cores diferentes",
			"1 lata de leite condensado",
			"1 lata de creme de leite",
			"1 envelope de gelatina sem sabor",
		],
		instructions: [
			"Prepare as gelatinas coloridas separadamente e leve para gelar até firmar. Corte em cubos.",
			"Hidrate a gelatina sem sabor e bata no liquidificador com o leite condensado e o creme de leite.",
			"Misture o creme com os cubos de gelatina colorida e leve para gelar novamente.",
		],
	},
	{
		id: "54",
		title: "🥪 Sanduíche de Pasta de Amendoim e Geleia",
		description:
			"O clássico americano 'PB&J'. Uma combinação surpreendente de pasta de amendoim salgada com geleia doce.",
		image:
			"https://images.unsplash.com/photo-1618183696-104241423015?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"2 fatias de pão de forma",
			"2 colheres de sopa de pasta de amendoim",
			"1 colher de sopa de geleia de sua preferência",
		],
		instructions: [
			"Espalhe a pasta de amendoim em uma fatia de pão.",
			"Espalhe a geleia na outra fatia.",
			"Junte as duas fatias e seu sanduíche está pronto.",
		],
	},
	{
		id: "55",
		title: "🍗 Tiras de Frango Crocantes (Tenders)",
		description:
			"Tiras de peito de frango empanadas em uma mistura especial que as deixa super crocantes por fora e macias por dentro.",
		image:
			"https://images.unsplash.com/photo-1626728043233-4a78a3a59408?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"300g de peito de frango em tiras",
			"1 ovo",
			"1 xícara de farinha de rosca com flocos de milho triturados",
			"Sal e páprica",
		],
		instructions: [
			"Tempere as tiras de frango com sal e páprica.",
			"Passe cada tira no ovo batido e depois na mistura de farinha de rosca e flocos de milho.",
			"Frite em óleo quente ou asse na airfryer a 200°C por 15 minutos.",
		],
	},
	{
		id: "56",
		title: "🥗 Salada de Macarrão Fria",
		description:
			"Uma salada completa e refrescante, perfeita para dias quentes ou para levar em um piquenique. ",
		image:
			"https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"200g de macarrão parafuso cozido",
			"1/2 xícara de tomate cereja",
			"1/2 xícara de queijo em cubos",
			"Azeitonas pretas",
			"Maionese ou iogurte para o molho",
		],
		instructions: [
			"Cozinhe o macarrão e deixe esfriar.",
			"Em uma tigela, misture o macarrão frio com o tomate, o queijo e as azeitonas.",
			"Adicione a maionese ou iogurte e misture bem.",
			"Tempere com sal e sirva gelada.",
		],
	},
	{
		id: "57",
		title: "🍪 Cookies com Gotas de Chocolate",
		description:
			"A receita clássica de cookies americanos: crocantes nas bordas, macios no meio e cheios de gotas de chocolate.",
		image:
			"https://images.unsplash.com/photo-1598184291252-154d4778e1a3?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"100g de manteiga amolecida",
			"1/2 xícara de açúcar",
			"1 ovo",
			"1 xícara de farinha de trigo",
			"1/2 colher de chá de fermento",
			"1 xícara de gotas de chocolate",
		],
		instructions: [
			"Misture a manteiga com o açúcar. Adicione o ovo e bata bem.",
			"Incorpore a farinha e o fermento.",
			"Por último, adicione as gotas de chocolate.",
			"Faça bolinhas, achate-as em uma forma e asse a 180°C por 12-15 minutos.",
		],
	},
	{
		id: "58",
		title: "🍴 Quibe Frito",
		description:
			"Um salgado clássico da culinária árabe, com uma casquinha crocante e um recheio saboroso de carne moída.",
		image:
			"https://images.unsplash.com/photo-1569562211093-429d3799aa3f?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"250g de trigo para quibe",
			"250g de carne moída",
			"1/2 cebola picada",
			"Hortelã picada",
			"Sal e pimenta síria",
		],
		instructions: [
			"Hidrate o trigo em água quente por 15 minutos e escorra bem.",
			"Misture o trigo com a carne moída, a cebola, a hortelã e os temperos.",
			"Modele os quibes.",
			"Frite em óleo quente até dourar.",
		],
	},
	{
		id: "59",
		title: "🍓 Pavê de Morango Simples",
		description:
			"Camadas de creme branco, biscoitos e morangos frescos. Uma sobremesa fácil, bonita e que não vai ao fogo.",
		image:
			"https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 lata de leite condensado",
			"1 lata de creme de leite",
			"1 pacote de biscoito maisena",
			"1 caixa de morangos picados",
			"Leite para umedecer os biscoitos",
		],
		instructions: [
			"Misture o leite condensado e o creme de leite para fazer o creme.",
			"Em uma travessa, faça uma camada de creme.",
			"Umedeça os biscoitos no leite e faça uma camada sobre o creme.",
			"Faça uma camada de morangos picados.",
			"Repita as camadas e finalize com creme e morangos. Leve para gelar.",
		],
	},
	{
		id: "60",
		title: "🍚 Arroz de Brócolis",
		description:
			"Uma forma simples de deixar o arroz do dia a dia mais nutritivo e saboroso, com brócolis e alho.",
		image:
			"https://images.unsplash.com/photo-1599493356244-23b8a7bd2d05?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"1 xícara de arroz",
			"2 xícaras de água",
			"1 xícara de brócolis picado",
			"2 dentes de alho picados",
			"Azeite e sal",
		],
		instructions: [
			"Refogue o alho no azeite.",
			"Adicione o arroz e refogue mais um pouco.",
			"Acrescente a água e o sal. Cozinhe em fogo baixo.",
			"Quando a água estiver quase secando, adicione o brócolis picado e misture. Tampe e termine o cozimento.",
		],
	},
	{
		id: "61",
		title: "🍤 Risoto de Camarão",
		description:
			"Um prato sofisticado, mas surpreendentemente fácil. Risoto cremoso com camarões suculentos e um toque de limão.",
		image:
			"https://images.unsplash.com/photo-1622139283984-8a3d7c56a0a4?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "25 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-03",
		ingredients: [
			"1 xícara de arroz arbóreo",
			"200g de camarão",
			"Caldo de legumes",
			"1/2 cebola",
			"Queijo parmesão",
			"Suco de 1/2 limão",
		],
		instructions: [
			"Refogue a cebola e o arroz.",
			"Adicione o caldo aos poucos, mexendo sempre.",
			"Quando o arroz estiver quase no ponto, adicione os camarões e o suco de limão. Cozinhe por 3 minutos.",
			"Finalize com queijo parmesão e manteiga.",
		],
	},
	{
		id: "62",
		title: "🥪 Sanduíche de Queijo Grelhado",
		description:
			"O 'grilled cheese' perfeito: pão dourado na manteiga com muito queijo derretido por dentro. Simples e reconfortante.",
		image:
			"https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"2 fatias de pão de forma",
			"2 fatias de queijo (cheddar ou muçarela)",
			"Manteiga",
		],
		instructions: [
			"Passe manteiga em um lado de cada fatia de pão.",
			"Coloque uma fatia na frigideira, com o lado da manteiga para baixo.",
			"Adicione o queijo e cubra com a outra fatia (manteiga para cima).",
			"Grelhe em fogo baixo até dourar dos dois lados e o queijo derreter.",
		],
	},
	{
		id: "63",
		title: "🍮 Creme de Baunilha (Pâtissière)",
		description:
			"Um creme de confeiteiro clássico, aveludado e com um intenso sabor de baunilha. Perfeito para rechear sonhos, tortas e éclairs.",
		image:
			"https://images.unsplash.com/photo-1617343248399-96b38832c8f9?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"250ml de leite",
			"2 gemas",
			"3 colheres de sopa de açúcar",
			"1 colher de sopa de amido de milho",
			"Essência de baunilha",
		],
		instructions: [
			"Aqueça o leite com a baunilha.",
			"Bata as gemas com o açúcar e o amido.",
			"Despeje o leite quente sobre a mistura de gemas, mexendo sempre.",
			"Volte tudo para a panela e cozinhe em fogo baixo, mexendo, até engrossar.",
		],
	},
	{
		id: "64",
		title: "🥗 Salada de Tomate com Manjericão",
		description:
			"A combinação mais clássica e perfeita. Tomates frescos e maduros com folhas de manjericão, regados com um bom azeite.",
		image:
			"https://images.unsplash.com/photo-1561043433-9265f837ce28?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"2 tomates grandes e maduros",
			"Folhas de manjericão fresco",
			"Azeite de oliva extra virgem",
			"Sal e pimenta do reino",
		],
		instructions: [
			"Fatie os tomates e disponha em um prato.",
			"Rasgue as folhas de manjericão e espalhe por cima.",
			"Regue generosamente com azeite.",
			"Tempere com sal e pimenta a gosto.",
		],
	},
	{
		id: "65",
		title: "🍗 Frango com Molho de Mostarda e Mel",
		description:
			"Um molho agridoce que transforma o simples filé de frango. A combinação de mostarda e mel é irresistível.",
		image:
			"https://images.unsplash.com/photo-1604503468807-3657f739d8a2?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"2 filés de frango",
			"2 colheres de sopa de mostarda dijon",
			"1 colher de sopa de mel",
			"Creme de leite (opcional)",
			"Sal e pimenta",
		],
		instructions: [
			"Tempere e grelhe os filés de frango. Reserve.",
			"Na mesma frigideira, misture a mostarda e o mel (e o creme de leite, se usar).",
			"Aqueça o molho por 1 minuto.",
			"Sirva o molho sobre os filés de frango.",
		],
	},
	{
		id: "66",
		title: "🍫 Fondue de Chocolate Fácil",
		description:
			"Uma sobremesa divertida e interativa. Chocolate derretido cremoso, perfeito para mergulhar frutas e marshmallows.",
		image:
			"https://images.unsplash.com/photo-1625937326484-a3341aa4338a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"200g de chocolate meio amargo picado",
			"1 caixinha de creme de leite",
			"Frutas picadas (morango, uva, banana)",
			"Marshmallows",
		],
		instructions: [
			"Derreta o chocolate em banho-maria ou no micro-ondas.",
			"Misture o creme de leite ao chocolate derretido até ficar homogêneo.",
			"Transfira para uma panela de fondue para manter aquecido.",
			"Sirva com as frutas e marshmallows.",
		],
	},
	{
		id: "67",
		title: "🥟 Pastel de Queijo",
		description:
			"O clássico de feira na sua casa. Massa crocante e sequinha com um recheio de queijo que derrete na boca.",
		image:
			"https://images.unsplash.com/photo-1617470715838-279b1e4a0343?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"1 rolo de massa para pastel",
			"200g de queijo muçarela ralado",
			"Orégano a gosto",
			"Óleo para fritar",
		],
		instructions: [
			"Abra a massa de pastel e corte no tamanho desejado.",
			"Recheie com o queijo e uma pitada de orégano.",
			"Feche bem as bordas com um garfo.",
			"Frite em óleo quente até a massa ficar dourada e crocante.",
		],
	},
	{
		id: "68",
		title: "🍓 Milkshake de Morango",
		description:
			"Cremoso, gelado e cheio de sabor. Um milkshake clássico feito com sorvete e morangos frescos.",
		image:
			"https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-09",
		ingredients: [
			"3 bolas de sorvete de creme",
			"1/2 xícara de morangos frescos ou congelados",
			"1/4 de xícara de leite",
		],
		instructions: [
			"Coloque todos os ingredientes no liquidificador.",
			"Bata até a mistura ficar cremosa e homogênea.",
			"Sirva imediatamente em um copo alto.",
			"Decore com um morango na borda.",
		],
	},
	{
		id: "69",
		title: "🍝 Macarrão com Brócolis e Alho",
		description:
			"Um prato de massa simples, leve e saboroso. A combinação de brócolis, alho e azeite é infalível.",
		image:
			"https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-01",
		ingredients: [
			"200g de macarrão",
			"1 maço de brócolis",
			"3 dentes de alho fatiados",
			"Azeite",
			"Pimenta calabresa (opcional)",
		],
		instructions: [
			"Cozinhe o macarrão e o brócolis (pode ser na mesma panela).",
			"Em uma frigideira, doure o alho fatiado no azeite.",
			"Adicione uma pitada de pimenta calabresa, se gostar.",
			"Escorra o macarrão e o brócolis e misture com o alho e óleo.",
		],
	},
	{
		id: "70",
		title: "🍮 Panna Cotta com Calda de Frutas",
		description:
			"Uma sobremesa italiana elegante e sedosa. Creme de leite cozido que derrete na boca, servido com uma calda azedinha.",
		image:
			"https://images.unsplash.com/photo-1567197998403-33907f2a8e18?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"500ml de creme de leite fresco",
			"1/2 xícara de açúcar",
			"1 colher de chá de essência de baunilha",
			"1/2 envelope de gelatina em pó sem sabor",
			"Frutas vermelhas para a calda",
		],
		instructions: [
			"Hidrate a gelatina em um pouco de água.",
			"Aqueça o creme de leite com o açúcar e a baunilha, sem ferver.",
			"Dissolva a gelatina hidratada no creme quente.",
			"Distribua em forminhas e leve para gelar por 4 horas. Sirva com a calda.",
		],
	},
	{
		id: "71",
		title: "🥗 Salada de Grão-de-Bico",
		description:
			"Uma salada nutritiva, rica em proteínas e muito saborosa. Ótima como acompanhamento ou prato principal leve.",
		image:
			"https://images.unsplash.com/photo-1582450871972-ab2427023712?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1 lata de grão-de-bico cozido e escorrido",
			"1/2 tomate picado",
			"1/4 de cebola roxa picada",
			"Salsinha picada",
			"Suco de limão e azeite",
		],
		instructions: [
			"Em uma tigela, misture o grão-de-bico, o tomate, a cebola e a salsinha.",
			"Tempere com suco de limão, azeite e sal.",
			"Misture bem e sirva.",
		],
	},
	{
		id: "72",
		title: "🍋 Frango com Limão e Ervas",
		description:
			"Filés de frango grelhados e finalizados com um molho vibrante de limão e ervas frescas. Leve, rápido e aromático.",
		image:
			"https://images.unsplash.com/photo-1630401781747-397353b85803?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"2 filés de frango",
			"Suco de 1 limão siciliano",
			"Ervas frescas picadas (alecrim, tomilho)",
			"Azeite",
			"Sal e pimenta",
		],
		instructions: [
			"Tempere os filés com sal, pimenta e metade do suco de limão.",
			"Grelhe os filés no azeite até dourarem.",
			"Na mesma frigideira, adicione o restante do suco de limão e as ervas, formando um molho rápido.",
			"Sirva o frango com o molho por cima.",
		],
	},
	{
		id: "73",
		title: "🍫 Bolo de Caneca de Chocolate",
		description:
			"A solução para aquela vontade de doce que aparece de repente. Um bolinho de chocolate fofinho, pronto em 5 minutos no micro-ondas.",
		image:
			"https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"1 ovo",
			"4 colheres de sopa de leite",
			"3 colheres de sopa de óleo",
			"4 colheres de sopa de farinha de trigo",
			"4 colheres de sopa de açúcar",
			"2 colheres de sopa de chocolate em pó",
			"1/2 colher de chá de fermento",
		],
		instructions: [
			"Em uma caneca, misture o ovo, o leite e o óleo.",
			"Adicione os ingredientes secos (farinha, açúcar, chocolate, fermento) e misture bem até ficar homogêneo.",
			"Leve ao micro-ondas por 3 minutos em potência alta.",
		],
	},
	{
		id: "74",
		title: "🥪 Sanduíche de Frango com Abacate",
		description:
			"Uma combinação moderna e saudável. Frango desfiado cremoso com a suavidade do abacate em um pão macio.",
		image:
			"https://images.unsplash.com/photo-1625194659829-60a88c19434a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-02",
		ingredients: [
			"100g de frango cozido e desfiado",
			"1/2 abacate amassado",
			"Suco de limão",
			"2 fatias de pão",
			"Sal e coentro",
		],
		instructions: [
			"Misture o frango desfiado com o abacate amassado.",
			"Tempere com suco de limão, sal e coentro.",
			"Recheie o pão com a mistura.",
			"Sirva imediatamente.",
		],
	},
	{
		id: "75",
		title: "🍮 Cheesecake de Pote",
		description:
			"Toda a delícia do cheesecake, sem o trabalho. Camadas de farofa de biscoito, creme de queijo e calda de frutas em um pote.",
		image:
			"https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "15 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"100g de cream cheese",
			"3 colheres de sopa de leite condensado",
			"Suco de 1/2 limão",
			"Biscoito maisena triturado",
			"Geleia de frutas vermelhas",
		],
		instructions: [
			"Misture o cream cheese, o leite condensado e o suco de limão até formar um creme liso.",
			"Em um pote, faça uma camada de biscoito triturado.",
			"Cubra com o creme de queijo.",
			"Finalize com uma camada de geleia. Leve para gelar.",
		],
	},
	{
		id: "76",
		title: "🍍 Salada de Abacaxi com Hortelã",
		description:
			"Uma sobremesa ou acompanhamento super refrescante. Cubos de abacaxi doce com o frescor da hortelã.",
		image:
			"https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "10 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-06",
		ingredients: [
			"1/2 abacaxi em cubos",
			"Folhas de hortelã fresca picadas",
			"Raspas de limão (opcional)",
		],
		instructions: [
			"Em uma tigela, misture os cubos de abacaxi com as folhas de hortelã picadas.",
			"Adicione as raspas de limão, se desejar, para um toque extra de frescor.",
			"Misture delicadamente e sirva gelada.",
		],
	},
	{
		id: "77",
		title: "🍅 Frango com Tomate Seco e Rúcula",
		description:
			"Um prato com sotaque italiano. Filé de frango grelhado, coberto com um molho cremoso de tomate seco e finalizado com rúcula.",
		image:
			"https://images.unsplash.com/photo-1633342249382-423375f43a68?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-05",
		ingredients: [
			"2 filés de frango",
			"1/4 xícara de tomate seco picado",
			"2 colheres de sopa de creme de leite",
			"Rúcula para finalizar",
			"Sal e pimenta",
		],
		instructions: [
			"Grelhe os filés de frango e reserve.",
			"Na mesma frigideira, adicione o tomate seco e o creme de leite, e aqueça.",
			"Sirva o molho sobre o frango e finalize com folhas de rúcula fresca.",
		],
	},
	{
		id: "78",
		title: "🍫 Trufa de Chocolate Fácil",
		description:
			"Trufas cremosas que derretem na boca, feitas com apenas dois ingredientes. Perfeitas para presentear ou para um café.",
		image:
			"https://images.unsplash.com/photo-1580823658225-a10a3c687c5a?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.8,
		isPublic: true,
		categoryId: "cat-04",
		ingredients: [
			"200g de chocolate meio amargo",
			"100g de creme de leite",
			"Cacau em pó para enrolar",
		],
		instructions: [
			"Derreta o chocolate e misture com o creme de leite até formar uma ganache lisa.",
			"Leve à geladeira por pelo menos 1 hora, ou até firmar.",
			"Faça bolinhas com a massa e passe no cacau em pó.",
		],
	},
	{
		id: "79",
		title: "🍚 Bolinho de Arroz",
		description:
			"A melhor forma de reaproveitar o arroz do dia anterior. Bolinhos crocantes por fora, macios por dentro e cheios de sabor.",
		image:
			"https://images.unsplash.com/photo-1615880142294-4e8536f3934f?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "20 min",
		rating: 4.7,
		isPublic: true,
		categoryId: "cat-08",
		ingredients: [
			"2 xícaras de arroz cozido",
			"1 ovo",
			"1/2 xícara de queijo ralado",
			"Cheiro-verde picado",
			"2 colheres de sopa de farinha de trigo",
			"Óleo para fritar",
		],
		instructions: [
			"Misture todos os ingredientes (exceto o óleo) em uma tigela.",
			"Modele os bolinhos com a ajuda de uma colher.",
			"Frite em óleo quente até ficarem dourados e crocantes.",
			"Escorra em papel toalha.",
		],
	},
	{
		id: "80",
		title: "🍉 Suco de Melancia com Gengibre",
		description:
			"Uma bebida super refrescante e com um toque picante do gengibre. Perfeita para hidratar nos dias quentes.",
		image:
			"https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=300&fit=crop",
		difficulty: "Fácil",
		time: "5 min",
		rating: 4.6,
		isPublic: true,
		categoryId: "cat-09",
		ingredients: [
			"2 fatias grossas de melancia sem sementes",
			"1 pedaço pequeno de gengibre (aprox. 1cm)",
			"Folhas de hortelã (opcional)",
		],
		instructions: [
			"Pique a melancia e descasque o gengibre.",
			"Bata tudo no liquidificador.",
			"Passe por uma peneira, se preferir um suco mais liso.",
			"Sirva imediatamente com gelo.",
		],
	},
];
