export const recipes = [
  {
    id: 1,
    title: "🍝 Carbonara Rápida e Saborosa",
    description: "Um prato italiano clássico, com molho cremoso de ovos, queijo pecorino e bacon crocante. Fácil de fazer e irresistível!",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 2,
    title: "🍔 Hambúrguer Smash Suculento",
    description: "Hambúrguer com crosta crocante e interior suculento, feito em minutos na chapa. Perfeito para um lanche rápido e delicioso!",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.7,
  },
  {
    id: 3,
    title: "🐟 Ceviche Peruano Refrescante",
    description: "Peixe fresco com limão, pimenta e coentro. Um prato leve, rápido e cheio de sabor, ideal para dias quentes!",
    image: "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.9,
  },
  {
    id: 4,
    title: "☕ Tiramisù Cremoso",
    description: "Sobremesa italiana com camadas de biscoito, café e creme de mascarpone. Fácil, sem forno e absolutamente deliciosa!",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.9,
  },
  {
    id: 5,
    title: "🍗 Frango Xadrez Colorido",
    description: "Frango com pimentões, cebola e amendoim em molho agridoce. Um prato rápido, vibrante e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1598515598523-245484a87aa4?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 6,
    title: "🌮 Tacos al Pastor Caseiros",
    description: "Tacos mexicanos com porco e abacaxi, cheios de sabor. Simples de preparar e perfeitos para qualquer ocasião!",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.9,
  },
  {
    id: 7,
    title: "🍜 Pad Thai Rápido",
    description: "Macarrão de arroz frito com camarão, tofu e molho agridoce. Um prato tailandês fácil, rápido e incrivelmente gostoso!",
    image: "https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 8,
    title: "🥗 Salada Caprese",
    description: "Tomate, muçarela de búfala e manjericão fresco com azeite de oliva. Uma salada italiana refrescante e pronta em minutos!",
    image: "https://images.unsplash.com/photo-1595854341625-f8ee9e6a1118?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.7,
  },
  {
    id: 9,
    title: "🥪 Sanduíche de Frango Grelhado",
    description: "Peito de frango grelhado com alface, tomate e maionese em pão macio. Um lanche rápido e delicioso para qualquer hora!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 10,
    title: "🍳 Omelete de Queijo e Ervas",
    description: "Ovos batidos com queijo derretido e ervas frescas. Simples, rápido e perfeito para o café da manhã ou jantar leve!",
    image: "https://images.unsplash.com/photo-1519671482749-f0462ced1e78?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.5,
  },
  {
    id: 11,
    title: "🥞 Panquecas Fofas",
    description: "Panquecas leves e douradas, perfeitas com mel, frutas ou geleia. Fáceis de fazer e ideais para um café da manhã especial!",
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 12,
    title: "🍲 Sopa de Abóbora Cremosa",
    description: "Sopa aveludada de abóbora com toque de creme de leite. Fácil, reconfortante e pronta em poucos minutos!",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 13,
    title: "🍤 Camarão ao Alho",
    description: "Camarões salteados com alho, azeite e salsinha. Um prato rápido, saboroso e perfeito para impressionar!",
    image: "https://images.unsplash.com/photo-1518709266092-863c52d1274f?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.9,
  },
  {
    id: 14,
    title: "🥙 Wrap de Atum",
    description: "Atum, alface, tomate e maionese em uma tortilla macia. Um lanche saudável e rápido para qualquer momento!",
    image: "https://images.unsplash.com/photo-1559054663-e8d7d0e8d4e6?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 15,
    title: "🍅 Bruschetta de Tomate",
    description: "Pão torrado com tomate fresco, manjericão e azeite. Uma entrada italiana simples e cheia de sabor!",
    image: "https://images.unsplash.com/photo-1504470690775-c1a68996e804?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 16,
    title: "🍴 Macarrão com Molho Pesto",
    description: "Macarrão com molho de manjericão, parmesão e nozes. Rápido, fresco e perfeito para um jantar leve!",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 17,
    title: "🥗 Salada de Frango Caesar",
    description: "Alface crocante, frango grelhado, croutons e molho Caesar. Uma salada clássica e fácil de preparar!",
    image: "https://images.unsplash.com/photo-1550305080-4e029753abcf?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 18,
    title: "🍕 Pizza de Frigideira",
    description: "Pizza caseira feita na frigideira com molho de tomate, queijo e seus toppings favoritos. Rápida e deliciosa!",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.7,
  },
  {
    id: 19,
    title: "🥑 Guacamole Caseiro",
    description: "Abacate cremoso com limão, tomate, cebola e coentro. Perfeito com nachos ou como acompanhamento!",
    image: "https://images.unsplash.com/photo-1583224964977-1e0a5e0b1d6a?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.9,
  },
  {
    id: 20,
    title: "🍓 Smoothie de Morango e Banana",
    description: "Smoothie refrescante com morangos, banana e iogurte. Ideal para um lanche rápido ou café da manhã saudável!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 21,
    title: "🥚 Ovos Mexidos Cremosos",
    description: "Ovos batidos cozidos lentamente com um toque de creme de leite. Simples, rápido e perfeito para o café da manhã!",
    image: "https://images.unsplash.com/photo-1493809842364-7887b4e7d7a8?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.7,
  },
  {
    id: 22,
    title: "🥖 Torrada com Abacate",
    description: "Pão torrado com abacate cremoso, limão e um toque de sal. Um café da manhã saudável e rápido!",
    image: "https://images.unsplash.com/photo-1515037027079-26d4b72e7c07?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.8,
  },
  {
    id: 23,
    title: "🍴 Penne ao Molho de Tomate",
    description: "Macarrão penne com molho de tomate caseiro e manjericão. Um prato simples e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 24,
    title: "🥗 Salada de Quinoa",
    description: "Quinoa com tomate cereja, pepino, cebola roxa e molho de limão. Leve, saudável e pronta em minutos!",
    image: "https://images.unsplash.com/photo-1490902931841-9c12e8e8d447?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.7,
  },
  {
    id: 25,
    title: "🍗 Nuggets Caseiros",
    description: "Pedaços de frango empanados e fritos até ficarem crocantes. Fácil e perfeito para crianças e adultos!",
    image: "https://images.unsplash.com/photo-1562967916-eb82221dfb32?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 26,
    title: "🍮 Pudim de Iogurte",
    description: "Sobremesa leve com iogurte, leite condensado e gelatina. Fácil de fazer e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.6,
  },
  {
    id: 27,
    title: "🥟 Bolinho de Milho",
    description: "Bolinhos fritos de milho com queijo, crocantes por fora e macios por dentro. Um petisco rápido e saboroso!",
    image: "https://images.unsplash.com/photo-1598511757336-2e5f21d5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 28,
    title: "🍵 Chá Gelado de Hibisco",
    description: "Chá refrescante de hibisco com limão e um toque de açúcar. Perfeito para dias quentes!",
    image: "https://images.unsplash.com/photo-1595968452573-7f43e6a7e317?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 29,
    title: "🥘 Arroz com Frango",
    description: "Arroz soltinho com pedaços de frango e temperos simples. Um prato caseiro e rápido para o dia a dia!",
    image: "https://images.unsplash.com/photo-1563379091339-246975ff92d1?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 30,
    title: "🍫 Mousse de Chocolate",
    description: "Mousse cremosa de chocolate feita com poucos ingredientes. Uma sobremesa fácil e irresistível!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.9,
  },
  {
    id: 31,
    title: "🥩 Carne Moída com Batata",
    description: "Carne moída refogada com batatas e temperos. Um prato simples, rápido e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.6,
  },
  {
    id: 32,
    title: "🍎 Torta de Maçã Rápida",
    description: "Torta de maçã com massa pronta e recheio de maçãs frescas. Fácil e perfeita para a sobremesa!",
    image: "https://images.unsplash.com/photo-1562008118-2d25b8b5c3a5?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 33,
    title: "🥒 Salada de Pepino Japonesa",
    description: "Pepino fatiado com molho de soja, vinagre de arroz e gergelim. Uma salada leve e refrescante!",
    image: "https://images.unsplash.com/photo-1611599534823-4d30e0dfe6a1?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 34,
    title: "🍤 Tempurá de Legumes",
    description: "Legumes crocantes fritos em massa leve de tempurá. Fácil, rápido e perfeito como acompanhamento!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b596c0b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 35,
    title: "🥐 Croissant com Presunto e Queijo",
    description: "Croissant recheado com presunto e queijo derretido. Um lanche rápido e delicioso!",
    image: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 36,
    title: "🍝 Espaguete com Almôndegas",
    description: "Espaguete com molho de tomate e almôndegas caseiras. Um prato clássico e fácil de preparar!",
    image: "https://images.unsplash.com/photo-1551892374-2d03e4b3a01a?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 37,
    title: "🍇 Salada de Frutas",
    description: "Mistura de frutas frescas com um toque de suco de laranja. Uma sobremesa leve e saudável!",
    image: "https://images.unsplash.com/photo-1583051747203-14f45e1e1a00?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 38,
    title: "🍗 Asinha de Frango Assada",
    description: "Asinhas temperadas e assadas até ficarem crocantes. Perfeito para um petisco rápido!",
    image: "https://images.unsplash.com/photo-1562967916-eb82221dfb32?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 39,
    title: "🍅 Sopa de Tomate",
    description: "Sopa cremosa de tomate com manjericão. Fácil, reconfortante e pronta em poucos minutos!",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744b22?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 40,
    title: "🥪 Sanduíche de Pasta de Atum",
    description: "Pasta de atum com maionese e cebola em pão fresquinho. Um lanche rápido e saboroso!",
    image: "https://images.unsplash.com/photo-1559054663-e8d7d0e8d4e6?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 41,
    title: "🍤 Salada de Camarão",
    description: "Camarões cozidos com alface, tomate e molho de iogurte. Leve, fresco e rápido de preparar!",
    image: "https://images.unsplash.com/photo-1518709266092-863c52d1274f?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 42,
    title: "🥚 Salada de Ovo",
    description: "Ovos cozidos com maionese, mostarda e cebolinha. Perfeito para rechear sanduíches ou comer com salada!",
    image: "https://images.unsplash.com/photo-1519671482749-f0462ced1e78?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 43,
    title: "🍮 Flan de Baunilha",
    description: "Flan cremoso com calda de caramelo. Uma sobremesa fácil e clássica que agrada a todos!",
    image: "https://images.unsplash.com/photo-1541783245547-a3d604567240?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 44,
    title: "🥗 Salada Grega",
    description: "Tomate, pepino, cebola roxa, azeitonas e queijo feta com azeite. Uma salada mediterrânea refrescante!",
    image: "https://images.unsplash.com/photo-1519671482749-f0462ced1e78?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.8,
  },
  {
    id: 45,
    title: "🍝 Macarrão com Queijo",
    description: "Macarrão com molho cremoso de queijo cheddar. Um prato reconfortante e rápido de fazer!",
    image: "https://images.unsplash.com/photo-1529042410759-befb5e7b41b6?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 46,
    title: "🍴 Risoto de Parmesão",
    description: "Risoto cremoso com queijo parmesão e um toque de manteiga. Fácil e perfeito para um jantar especial!",
    image: "https://images.unsplash.com/photo-1595908129324-1a7333a0a3a4?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 47,
    title: "🥪 Sanduíche de Peru",
    description: "Peito de peru, alface, tomate e mostarda em pão integral. Um lanche saudável e rápido!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 48,
    title: "🍓 Sorvete de Morango Caseiro",
    description: "Sorvete cremoso de morango feito com poucos ingredientes. Fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a4f3?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 49,
    title: "🥘 Frango com Brócolis",
    description: "Peito de frango salteado com brócolis e molho de soja. Um prato saudável e rápido para o dia a dia!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 50,
    title: "🍫 Brownie de Caneca",
    description: "Brownie rápido feito no micro-ondas. Perfeito para uma sobremesa individual e deliciosa!",
    image: "https://images.unsplash.com/photo-1602351447937-745cb720f790?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.8,
  },
  {
    id: 51,
    title: "🥗 Salada de Rúcula com Parmesão",
    description: "Rúcula fresca com lascas de parmesão, nozes e molho de limão. Simples, elegante e pronta em minutos!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.7,
  },
  {
    id: 52,
    title: "🍴 Strogonoff de Frango",
    description: "Strogonoff cremoso com frango, creme de leite e champignon. Fácil e perfeito com arroz ou batata!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 53,
    title: "🍮 Gelatina de Morango",
    description: "Gelatina refrescante com pedaços de morango fresco. Uma sobremesa fácil e divertida!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 54,
    title: "🥪 Sanduíche de Pasta de Amendoim",
    description: "Pasta de amendoim com geleia em pão macio. Um lanche clássico e rápido para qualquer hora!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 55,
    title: "🍗 Tiras de Frango Crocantes",
    description: "Tiras de frango empanadas e fritas até dourarem. Um petisco fácil e perfeito para compartilhar!",
    image: "https://images.unsplash.com/photo-1562967916-eb82221dfb32?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 56,
    title: "🥗 Salada de Macarrão",
    description: "Macarrão com tomate, azeitonas, queijo e molho de mostarda. Uma salada fria e fácil de preparar!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 57,
    title: "🍫 Cookies de Chocolate",
    description: "Cookies crocantes com gotas de chocolate. Fáceis de fazer e perfeitos para um lanche doce!",
    image: "https://images.unsplash.com/photo-1499638673413-8789a160042d?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 58,
    title: "🍴 Quibe Frito",
    description: "Quibes crocantes recheados com carne moída e temperos. Um petisco fácil e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 59,
    title: "🍓 Pavê de Morango",
    description: "Camadas de creme, biscoito e morangos frescos. Uma sobremesa fácil e deliciosa!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 60,
    title: "🥘 Arroz de Brócolis",
    description: "Arroz com brócolis e alho, simples e saboroso. Um acompanhamento rápido para qualquer refeição!",
    image: "https://images.unsplash.com/photo-1563379091339-246975ff92d1?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 61,
    title: "🍤 Risoto de Camarão",
    description: "Risoto cremoso com camarões e toque de limão. Fácil e perfeito para ocasiões especiais!",
    image: "https://images.unsplash.com/photo-1595908129324-1a7333a0a3a4?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 62,
    title: "🥪 Sanduíche de Queijo Grelhado",
    description: "Pão com queijo derretido, dourado na frigideira. Um clássico rápido e reconfortante!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.7,
  },
  {
    id: 63,
    title: "🍮 Creme de Baunilha",
    description: "Creme suave de baunilha com textura aveludada. Uma sobremesa fácil e elegante!",
    image: "https://images.unsplash.com/photo-1541783245547-a3d604567240?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 64,
    title: "🥗 Salada de Tomate e Manjericão",
    description: "Tomate fatiado com manjericão fresco e azeite. Uma salada simples e refrescante!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 65,
    title: "🍴 Frango com Molho de Mostarda",
    description: "Peito de frango com molho cremoso de mostarda. Fácil, rápido e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 66,
    title: "🍫 Fondue de Chocolate",
    description: "Chocolate derretido com frutas frescas para mergulhar. Uma sobremesa fácil e divertida!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 67,
    title: "🥟 Pastel de Queijo",
    description: "Pastéis fritos com recheio de queijo derretido. Um petisco simples e delicioso!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 68,
    title: "🍓 Milkshake de Morango",
    description: "Milkshake cremoso com morangos frescos e sorvete de baunilha. Rápido e refrescante!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.8,
  },
  {
    id: 69,
    title: "🥘 Macarrão com Brócolis",
    description: "Macarrão com brócolis salteado e alho. Um prato simples, saudável e rápido!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 70,
    title: "🍮 Panna Cotta",
    description: "Sobremesa italiana cremosa com calda de frutas. Fácil e elegante para qualquer ocasião!",
    image: "https://images.unsplash.com/photo-1541783245547-a3d604567240?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 71,
    title: "🥗 Salada de Grão-de-Bico",
    description: "Grão-de-bico com tomate, cebola e salsa, temperado com azeite e limão. Saudável e rápido!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 72,
    title: "🍗 Frango com Limão",
    description: "Peito de frango grelhado com molho de limão e ervas. Um prato leve e saboroso!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 73,
    title: "🍫 Bolo de Caneca",
    description: "Bolo de chocolate rápido feito no micro-ondas. Perfeito para uma sobremesa individual!",
    image: "https://images.unsplash.com/photo-1602351447937-745cb720f790?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.8,
  },
  {
    id: 74,
    title: "🥪 Sanduíche de Frango com Abacate",
    description: "Frango desfiado com abacate e alface em pão macio. Um lanche saudável e rápido!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 75,
    title: "🍮 Cheesecake de Caneca",
    description: "Cheesecake rápido com base de biscoito e creme de queijo. Uma sobremesa fácil e deliciosa!",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.7,
  },
  {
    id: 76,
    title: "🥗 Salada de Abacaxi com Hortelã",
    description: "Abacaxi fresco com hortelã e um toque de mel. Uma salada doce e refrescante!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 77,
    title: "🍴 Frango com Tomate Seco",
    description: "Peito de frango com molho de tomate seco e manjericão. Fácil e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 78,
    title: "🍫 Trufa de Chocolate",
    description: "Trufas de chocolate com textura cremosa. Fáceis de fazer e perfeitas para presentear!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 79,
    title: "🥟 Bolinho de Arroz",
    description: "Bolinhos crocantes feitos com sobras de arroz e queijo. Um petisco fácil e econômico!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 80,
    title: "🍓 Suco de Melancia com Morango",
    description: "Suco refrescante de melancia e morango. Rápido, saudável e perfeito para o calor!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 81,
    title: "🥘 Macarrão com Atum",
    description: "Macarrão com atum e molho de tomate. Um prato simples e rápido para o dia a dia!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 82,
    title: "🍮 Sobremesa de Abacaxi",
    description: "Creme de abacaxi com leite condensado e biscoitos. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 83,
    title: "🥗 Salada de Manga",
    description: "Manga com rúcula, queijo e molho de mel. Uma salada doce e salgada, pronta em minutos!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 84,
    title: "🍗 Frango com Ervas",
    description: "Peito de frango grelhado com ervas frescas e limão. Um prato leve e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 85,
    title: "🍫 Brigadeiro de Colher",
    description: "Brigadeiro cremoso feito com leite condensado e chocolate. Uma sobremesa rápida e irresistível!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.8,
  },
  {
    id: 86,
    title: "🥟 Bolinho de Mandioca",
    description: "Bolinhos fritos de mandioca com queijo. Crocantes por fora e macios por dentro!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 87,
    title: "🍓 Smoothie de Manga",
    description: "Smoothie refrescante com manga, iogurte e um toque de mel. Perfeito para um lanche rápido!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 88,
    title: "🥘 Arroz com Ovo",
    description: "Arroz soltinho com ovo frito e cebolinha. Um prato simples e reconfortante para qualquer dia!",
    image: "https://images.unsplash.com/photo-1563379091339-246975ff92d1?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 89,
    title: "🍮 Mousse de Limão",
    description: "Mousse refrescante de limão com leite condensado. Fácil e perfeita para sobremesa!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.7,
  },
  {
    id: 90,
    title: "🥗 Salada de Alface com Frango",
    description: "Alface crocante com frango desfiado e molho de mostarda. Uma salada leve e rápida!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 91,
    title: "🍗 Frango com Curry",
    description: "Peito de frango com molho de curry e leite de coco. Um prato exótico e fácil de fazer!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.7,
  },
  {
    id: 92,
    title: "🍫 Bolinho de Chocolate",
    description: "Bolinhos macios de chocolate, perfeitos para um lanche rápido ou sobremesa!",
    image: "https://images.unsplash.com/photo-1602351447937-745cb720f790?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 93,
    title: "🥪 Sanduíche de Tomate e Queijo",
    description: "Tomate fresco, queijo e manjericão em pão torrado. Um lanche simples e saboroso!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 94,
    title: "🍮 Sobremesa de Manga",
    description: "Creme de manga com leite condensado e biscoitos. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 95,
    title: "🥗 Salada de Beterraba",
    description: "Beterraba ralada com cenoura, maçã e molho de iogurte. Uma salada colorida e saudável!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 96,
    title: "🍗 Frango com Pimentão",
    description: "Peito de frango salteado com pimentões coloridos e molho de soja. Rápido e saboroso!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 97,
    title: "🍫 Torta de Chocolate Rápida",
    description: "Torta de chocolate com base de biscoito. Fácil e perfeita para sobremesa!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 98,
    title: "🥟 Bolinho de Batata",
    description: "Bolinhos fritos de batata com queijo. Crocantes por fora e macios por dentro!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 99,
    title: "🍓 Suco de Laranja com Morango",
    description: "Suco refrescante de laranja com morangos frescos. Rápido e perfeito para o café da manhã!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 100,
    title: "🥘 Macarrão com Molho de Ervas",
    description: "Macarrão com molho de ervas frescas e azeite. Um prato simples e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 101,
    title: "🍮 Creme de Chocolate",
    description: "Creme de chocolate suave e aveludado. Uma sobremesa fácil e deliciosa!",
    image: "https://images.unsplash.com/photo-1541783245547-a3d604567240?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 102,
    title: "🥗 Salada de Cenoura com Passas",
    description: "Cenoura ralada com passas e molho de iogurte. Uma salada doce e refrescante!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 103,
    title: "🍗 Frango com Alho",
    description: "Peito de frango grelhado com alho e ervas. Um prato simples e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 104,
    title: "🍫 Brigadeiro de Caneca",
    description: "Brigadeiro rápido feito no micro-ondas. Perfeito para uma sobremesa individual!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.8,
  },
  {
    id: 105,
    title: "🥪 Sanduíche de Ovo com Bacon",
    description: "Ovo frito com bacon crocante em pão macio. Um lanche rápido e saboroso!",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.7,
  },
  {
    id: 106,
    title: "🍮 Sobremesa de Limão",
    description: "Creme de limão com leite condensado e biscoitos. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 107,
    title: "🥗 Salada de Abobrinha",
    description: "Abobrinha fatiada com limão, azeite e parmesão. Uma salada leve e refrescante!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 108,
    title: "🍗 Frango com Cebola",
    description: "Peito de frango salteado com cebolas caramelizadas. Simples, rápido e delicioso!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 109,
    title: "🍫 Muffin de Chocolate",
    description: "Muffins fofos de chocolate com gotas de chocolate. Fáceis e perfeitos para um lanche!",
    image: "https://images.unsplash.com/photo-1602351447937-745cb720f790?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 110,
    title: "🥟 Bolinho de Frango",
    description: "Bolinhos fritos de frango desfiado com temperos. Um petisco fácil e saboroso!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 111,
    title: "🍓 Suco de Abacaxi com Hortelã",
    description: "Suco refrescante de abacaxi com hortelã. Rápido e perfeito para o calor!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 112,
    title: "🥘 Macarrão com Manjericão",
    description: "Macarrão com molho de manjericão fresco e parmesão. Um prato simples e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 113,
    title: "🍮 Creme de Morango",
    description: "Creme de morango com leite condensado e biscoitos. Uma sobremesa fácil e deliciosa!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 114,
    title: "🥗 Salada de Tomate com Rúcula",
    description: "Tomate fresco com rúcula e molho de azeite. Uma salada simples e refrescante!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 115,
    title: "🍗 Frango com Milho",
    description: "Peito de frango salteado com milho e creme de leite. Um prato rápido e reconfortante!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 116,
    title: "🍫 Bolo de Chocolate Simples",
    description: "Bolo fofinho de chocolate com cobertura de ganache. Fácil e perfeito para qualquer ocasião!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 117,
    title: "🥟 Bolinho de Carne",
    description: "Bolinhos fritos de carne moída com temperos. Um petisco fácil e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 118,
    title: "🍓 Suco de Manga com Laranja",
    description: "Suco refrescante de manga com laranja. Rápido e perfeito para o café da manhã!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 119,
    title: "🥘 Macarrão com Frango",
    description: "Macarrão com frango desfiado e molho de tomate. Um prato simples e rápido!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 120,
    title: "🍮 Sobremesa de Chocolate",
    description: "Creme de chocolate com leite condensado e biscoitos. Uma sobremesa fácil e deliciosa!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 121,
    title: "🥗 Salada de Pepino com Iogurte",
    description: "Pepino fatiado com molho de iogurte e hortelã. Uma salada refrescante e rápida!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 122,
    title: "🍗 Frango com Champignon",
    description: "Peito de frango com molho cremoso de champignon. Fácil e perfeito para um jantar rápido!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 123,
    title: "🍫 Cupcake de Chocolate",
    description: "Cupcakes fofos de chocolate com cobertura cremosa. Fáceis e perfeitos para festas!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 124,
    title: "🥟 Bolinho de Queijo com Ervas",
    description: "Bolinhos fritos de queijo com ervas frescas. Um petisco fácil e saboroso!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 125,
    title: "🍓 Suco de Melão",
    description: "Suco refrescante de melão com um toque de limão. Rápido e perfeito para o calor!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 126,
    title: "🥘 Macarrão com Molho de Queijo",
    description: "Macarrão com molho cremoso de queijo parmesão. Um prato simples e reconfortante!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 127,
    title: "🍮 Creme de Manga",
    description: "Creme de manga com leite condensado e gelatina. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 128,
    title: "🥗 Salada de Frango com Maçã",
    description: "Frango desfiado com maçã, nozes e molho de iogurte. Uma salada leve e saborosa!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 129,
    title: "🍗 Frango com Ervas e Limão",
    description: "Peito de frango grelhado com ervas frescas e limão. Um prato leve e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 130,
    title: "🍫 Cookies de Baunilha",
    description: "Cookies crocantes de baunilha com toque de açúcar. Fáceis e perfeitos para um lanche!",
    image: "https://images.unsplash.com/photo-1499638673413-8789a160042d?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 131,
    title: "🥟 Bolinho de Camarão",
    description: "Bolinhos fritos de camarão com temperos. Um petisco fácil e delicioso!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 132,
    title: "🍓 Suco de Pêssego",
    description: "Suco refrescante de pêssego com um toque de limão. Rápido e perfeito para o calor!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 133,
    title: "🥘 Macarrão com Pesto de Rúcula",
    description: "Macarrão com molho de rúcula, parmesão e nozes. Um prato simples e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 134,
    title: "🍮 Sobremesa de Maracujá",
    description: "Creme de maracujá com leite condensado e biscoitos. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 135,
    title: "🥗 Salada de Tomate com Azeitonas",
    description: "Tomate fresco com azeitonas e molho de azeite. Uma salada simples e mediterrânea!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "10 min",
    rating: 4.6,
  },
  {
    id: 136,
    title: "🍗 Frango com Creme de Milho",
    description: "Peito de frango com molho cremoso de milho. Um prato rápido e reconfortante!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 137,
    title: "🍫 Torta de Limão Rápida",
    description: "Torta de limão com base de biscoito e creme azedo. Fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1574457547512-3a3a828f1074?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "25 min",
    rating: 4.8,
  },
  {
    id: 138,
    title: "🥟 Bolinho de Abobrinha",
    description: "Bolinhos fritos de abobrinha com queijo. Crocantes por fora e macios por dentro!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 139,
    title: "🍓 Suco de Uva",
    description: "Suco refrescante de uva com um toque de limão. Rápido e perfeito para o café da manhã!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 140,
    title: "🥘 Macarrão com Molho de Limão",
    description: "Macarrão com molho leve de limão e parmesão. Um prato simples e refrescante!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.6,
  },
  {
    id: 141,
    title: "🍮 Creme de Abacaxi",
    description: "Creme de abacaxi com leite condensado e gelatina. Uma sobremesa fácil e refrescante!",
    image: "https://images.unsplash.com/photo-1519996521430-76b6a7dabd50?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 142,
    title: "🥗 Salada de Brócolis",
    description: "Brócolis cozido com bacon crocante e molho de mostarda. Uma salada saborosa e rápida!",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "15 min",
    rating: 4.6,
  },
  {
    id: 143,
    title: "🍗 Frango com Pesto",
    description: "Peito de frango grelhado com molho de pesto de manjericão. Fácil e cheio de sabor!",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 144,
    title: "🍫 Cookies de Aveia e Chocolate",
    description: "Cookies crocantes de aveia com gotas de chocolate. Fáceis e perfeitos para um lanche!",
    image: "https://images.unsplash.com/photo-1499638673413-8789a160042d?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.8,
  },
  {
    id: 145,
    title: "🥟 Bolinho de Milho com Queijo",
    description: "Bolinhos fritos de milho com queijo derretido. Um petisco fácil e delicioso!",
    image: "https://images.unsplash.com/photo-1598511726614-0e7e2b5e37b?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  {
    id: 146,
    title: "🍓 Suco de Maçã com Canela",
    description: "Suco refrescante de maçã com um toque de canela. Rápido e perfeito para o café da manhã!",
    image: "https://images.unsplash.com/photo-1505252585461-04b627edde57?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "5 min",
    rating: 4.6,
  },
  {
    id: 147,
    title: "🥘 Macarrão com Camarão",
    description: "Macarrão com camarões salteados e molho de tomate. Um prato simples e elegante!",
    image: "https://images.unsplash.com/photo-1516108317508-a8d8d7f18b7e?w=400&h=300&fit=crop",
    difficulty: "Fácil",
    time: "20 min",
    rating: 4.7,
  },
  ]